# Generated by Django 2.2.6 on 2020-05-11 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200511_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='posted_when',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 2, 48, 41, 633021, tzinfo=utc)),
        ),
    ]
